set nocompatible 
set scrolloff=8 
set backupdir=~/.vim/tmp
set directory=~/.vim/tmp
set noerrorbells
set visualbell   
imap <C-?> <C-h>

if has("syntax")
  syn on
end
set t_Co=256

set shiftwidth=2      
set tabstop=2        
set expandtab       
set autoindent
set nosmartindent
set cindent        
set cinkeys=!^F      
set cinoptions=(0t0c1
set foldmethod=marker
set background=dark
set viminfo='50,\"1000,:100,n~/.viminfo
set noruler
set laststatus=2    
set showcmd        
set showmatch  
set ignorecase
set smartcase
set list    
set listchars=tab:>-
set matchpairs+=<:>
set complete=.,w,b,i,t,u
set backspace=indent,eol
set formatoptions=tocrqn
set comments=b:#,s1:/*,mb:\ *,ex:*/,f://

set titlestring=vim\ %<%F%(\ %)%m%h%w%=%l/%L-%P 
set titlelen=70
if &term == "screen"
  seet t_fs= t_tf &term == "screen" || &term == "xterm"
  set title
endif
if isdirectory("~/.vim/doc")
  helptags ~/.vim/doc
endif
filetype on
filetype plugin on
filetype plugin indent on

