execute pathogen#infect()
set nocompatible 
set backupdir=~/.vim/tmp
set directory=~/.vim/tmp
set noerrorbells
set visualbell   
set shiftwidth=2      
set tabstop=2        
set expandtab       
set autoindent
set showcmd        
set showmatch  
set ignorecase
set smartcase
set hlsearch
filetype on
filetype plugin on
filetype plugin indent on
